Key backup: add `PUT /room_keys/version/{version}`
uhoreg/matrix-doc pull request #1
Opened 2019-02-06 10:55 UTC by manuroe

to allow matrix clients to add signatures to an existing backup or update any information in the `auth_data` field.

2019-02-06 19:35 UTC, uhoreg requested changes
A couple of minor issues, but overall looks pretty good.  I'm wondering, though, if we should say that the server will ensure that the public key in the auth_data is the same as the previous value, though that means that the server must understand the different backup formats.

2019-02-06 19:35 UTC, uhoreg commented on proposals/1219-storing-megolm-keys-serverside.md
> +- `algorithm` (string): Optional. Must be the same as in the body parameters for `GET
AIUI, in REST, the contents of PUT are supposed to be the full object that is to be stored, so I think `algorithm` should be required.

2019-02-06 19:35 UTC, uhoreg commented on proposals/1219-storing-megolm-keys-serverside.md
> +Update information about the given version, or the current version if `{version}`
Having the `{version}` optional seems like it makes it a bit too easy for a client to accidentally overwrite a new backup version with an old backup version.  I think we should just make the `version` required.

2019-02-06 22:54 UTC, uhoreg commented
There's a race condition in this API for use with updating signatures.  If the user is setting up backup on two devices A and B, they both fetch the backup version info, and then both sign the backup info, and then both send their updates to the server, then the server will only end up with one of the signatures.  This might not be too bad in practice, but clients should do what they can to avoid this situation (e.g. re-fetching the backup info just before signing and sending, so that they have as much up-to-date information as they can get).

2019-02-07 09:55 UTC, manuroe commented
> I'm wondering, though, if we should say that the server will ensure that the public key in the auth_data is the same as the previous value, though that means that the server must understand the different backup formats.

Given we specify `m.megolm_backup.v1.curve25519-aes-sha2` in this spec, we could require the server to make additional check when encountering that format.

> There's a race condition in this API for use with updating signatures

You are right. Client should manage it.

2019-02-08 04:29 UTC, uhoreg approved these changes

2019-02-08 04:30 UTC, merged